# apps.tr.models

# django
from django.db import models

# local
from apps.client.models import Client, Project
from apps.users.models import User

# util

### Create your models here.

### PRODUCTS
class TranscriptionList(models.Model):
	'''
	This is the first final product of the process. It is simply a list of transcriptions,
	their best utterances, and the users that did them.

	It belongs to an end client and is part of a project: Project.generate_transcription_list()
	'''

	### Connections
	client = models.ForeignKey(Client, related_name='transcription_lists')
	project = models.ForeignKey(Project, related_name='transcription_lists')

	# sub: transcription, audiofile

	### Properties
	metadata = models.TextField(default='')
	date_created = models.DateTimeField(auto_now_add=True)
	file = models.FileField(upload_to='transcription-lists')

class Grammar(models.Model):
	'''
	This is the second final product. It is an XML document generated from the best utterances.

	It belongs to an end client and is part of a project: Project.generate_grammar()
	'''

	### Connections
	client = models.ForeignKey(Client, related_name='grammars')
	project = models.ForeignKey(Project, related_name='grammars')

	# sub: transcription, audiofile

	### Properties
	metadata = models.TextField(default='')
	date_created = models.DateTimeField(auto_now_add=True)
	file = models.FileField(upload_to='grammars')

### STRUCTURES
class Sample(models.Model):
	'''
	A set of transcriptions sampled from a single project to be subjected to a trial as a group.
	When such a group is transcribed, it can be used to generate an automatic grammar that will be
	applied to the rest of the project, or indeed, another sample. A single transcription can
	appear in multiple samples.

	'''

	### Connections
	client = models.ForeignKey(Client, related_name='samples')
	project = models.ForeignKey(Project, related_name='samples')

	### Properties

class Transcription(models.Model):
	'''
	The central object of the system. It is the connection between audio data and text utterances.

	'''

	### Connections
	client = models.ForeignKey(Client, related_name='transcriptions')
	project = models.ForeignKey(Project, related_name='transcriptions')

	### Properties
	original_utterance = models.CharField(max_length=255, default='')
	requests = models.IntegerField(default=0)
	date_created = models.DateTimeField(auto_now_add=True)
	date_last_requested = models.DateTimeField(auto_now=True)

	### Methods

class TranscriptionInstance(models.Model):
	'''
	A transcription as part of a sample.
	'''

	### Connections
	client = models.ForeignKey(Client, related_name='transcription_instances')
	project = models.ForeignKey(Project, related_name='transcription_instances')
	sample = models.ForeignKey(Sample, related_name='transcription_instances')

	### Properties
	requests = models.IntegerField(default=0)
	date_created = models.DateTimeField(auto_now_add=True)
	date_last_requested = models.DateTimeField(auto_now=True)

class RecognisedUtterance(models.Model):
	'''
	A text utterance generated by a speech recogniser.
	'''

	### Connections
	client = models.ForeignKey(Client, related_name='recognised_utterances')
	project = models.ForeignKey(Project, related_name='recognised_utterances')
	sample = models.ForeignKey(Sample, related_name='recognised_utterances')
	tr = models.ForeignKey(Transcription, related_name='recognised_utterances')
	tri = models.ForeignKey(Transcription, related_name='recognised_utterances')

	### Properties
	recogniser = models.CharField(max_length=255)
	text = models.TextField()
	metadata = models.TextField()
	date_created = models.DateTimeField(auto_now_add=True)

class UserUtterance(models.Model):
	'''
	A text utterance transcribed by a user.
	'''

	### Connections
	client = models.ForeignKey(Client, related_name='user_utterances')
	project = models.ForeignKey(Project, related_name='user_utterances')
	sample = models.ForeignKey(Sample, related_name='user_utterances')
	tr = models.ForeignKey(Transcription, related_name='user_utterances')
	tri = models.ForeignKey(Transcription, related_name='user_utterances')
	user = models.ForeignKey(User, related_name='utterances')

	### Properties
	text = models.TextField()
	metadata = models.TextField()
	date_created = models.DateTimeField(auto_now_add=True)

class UserComment(models.Model):
	'''
	A comment made on a transcription by the user.
	'''

	### Connections
	client = models.ForeignKey(Client, related_name='comments')
	project = models.ForeignKey(Project, related_name='comments')
	sample = models.ForeignKey(Sample, related_name='comments')
	tr = models.ForeignKey(Transcription, related_name='comments')
	tri = models.ForeignKey(Transcription, related_name='comments')
	user = models.ForeignKey(User, related_name='comments')

	### Properties
	text = models.TextField()
	date_created = models.DateTimeField(auto_now_add=True)

class Tag(models.Model):
	'''
	An add-on to a text utterance.
	'''

	### Properties
	name = models.CharField(max_length=255)
	text = models.CharField(max_length=255)
	is_client_specific = models.BooleanField(default=False)
	is_issue = models.BooleanField(default=False)

class TagInstance(models.Model):
	'''
	A tag connected to a transcription
	'''

	### Connections
	tag = models.ForeignKey(Tag, related_name='instances')
	client = models.ForeignKey(Client, related_name='tag_instances')
	project = models.ForeignKey(Project, related_name='tag_instances')
	sample = models.ForeignKey(Sample, related_name='tag_instances')
	tr = models.ForeignKey(Transcription, related_name='tag_instances')
	tri = models.ForeignKey(Transcription, related_name='tag_instances')
	utt = models.ForeignKey(UserUtterance, related_name='tag_instances')

	### Properties
	position = models.IntegerField(default=0)
