# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overwatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.BooleanField(default=True)),
                ('reason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OverwatchComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('overwatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overwatch_comments', to='tr.Overwatch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OverwatchModeration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.BooleanField(default=True)),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tr_overwatchmoderation_moderations', to='users.Moderator')),
                ('overwatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overwatch_moderations', to='tr.Overwatch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecogniserUtterance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('metadata', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('recogniser', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='client.ContractClient')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('shortcut', models.CharField(max_length=255)),
                ('is_issue', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tr_tag_tokens', to='client.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TagInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='tr.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_utterance', models.CharField(default='', max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('requests', models.PositiveIntegerField(default=0)),
                ('request_allowance', models.PositiveIntegerField(default=1)),
                ('request_allowance_threshold', models.PositiveIntegerField(default=3)),
                ('flagged_for_review', models.BooleanField(default=False)),
                ('date_last_requested', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to='client.Project')),
            ],
        ),
        migrations.CreateModel(
            name='UtteranceComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UtteranceModeration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.BooleanField(default=True)),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tr_utterancemoderation_moderations', to='users.Moderator')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=30)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tr_word_tokens', to='client.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WordInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkerUtterance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('metadata', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('transcription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tr_workerutterance_utterances', to='tr.Transcription')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utterances', to='users.Worker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='wordinstance',
            name='utterance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tr_wordinstance_token_instances', to='tr.WorkerUtterance'),
        ),
        migrations.AddField(
            model_name='wordinstance',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='tr.Word'),
        ),
        migrations.AddField(
            model_name='utterancemoderation',
            name='utterance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utterance_moderations', to='tr.WorkerUtterance'),
        ),
        migrations.AddField(
            model_name='utterancecomment',
            name='utterance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utterance_comments', to='tr.WorkerUtterance'),
        ),
        migrations.AddField(
            model_name='taginstance',
            name='utterance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tr_taginstance_token_instances', to='tr.WorkerUtterance'),
        ),
        migrations.AddField(
            model_name='recogniserutterance',
            name='transcription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tr_recogniserutterance_utterances', to='tr.Transcription'),
        ),
        migrations.AddField(
            model_name='overwatch',
            name='rules_cited',
            field=models.ManyToManyField(related_name='overwatches', to='tr.Rule'),
        ),
        migrations.AddField(
            model_name='overwatch',
            name='utterance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overwatches', to='tr.WorkerUtterance'),
        ),
        migrations.AddField(
            model_name='overwatch',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overwatches', to='users.Worker'),
        ),
    ]
