# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-25 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_moderator_comment', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('is_client_specific', models.BooleanField(default=False)),
                ('is_issue', models.BooleanField(default=False)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='client.Client')),
            ],
        ),
        migrations.CreateModel(
            name='TagInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='tr.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='TagInstanceManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_utterance', models.CharField(default='', max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('requests', models.PositiveIntegerField(default=0)),
                ('request_allowance', models.PositiveIntegerField(default=1)),
                ('request_allowance_threshold', models.PositiveIntegerField(default=3)),
                ('flagged_for_review', models.BooleanField(default=False)),
                ('date_last_requested', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to='client.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Utterance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_user_generated', models.BooleanField(default=True)),
                ('recogniser', models.CharField(default='user', max_length=255)),
                ('text', models.TextField()),
                ('metadata', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('transcription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utterances', to='tr.Transcription')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utterances', to='users.User')),
            ],
        ),
        migrations.AddField(
            model_name='taginstance',
            name='utterance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_instances', to='tr.Utterance'),
        ),
        migrations.AddField(
            model_name='comment',
            name='utterance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tr.Utterance'),
        ),
    ]
