# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 21:25
from __future__ import unicode_literals

import apps.audio.models.audio
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '__first__'),
        ('tr', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.audio.models.audio.rename_audio_file)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='client.Project')),
                ('transcription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='tr.Transcription')),
            ],
        ),
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.TextField(default='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='grammars')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammars', to='client.Project')),
            ],
        ),
    ]
