# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-16 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('priority_index', models.PositiveIntegerField(default=0)),
                ('due_date', models.DateTimeField(auto_now_add=True)),
                ('completion_percentage', models.FloatField(default=0.0)),
                ('redundancy_percentage', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_production', models.BooleanField(default=False)),
                ('is_contract', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('combined_priority_index', models.PositiveIntegerField(default=0)),
                ('completion_percentage', models.FloatField(default=0.0)),
                ('redundancy_percentage', models.FloatField(default=0.0)),
                ('contract_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_projects', to='client.Client')),
                ('production_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_projects', to='client.Client')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='client.Project'),
        ),
    ]
